name: Deb Static Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Rust Cargo Deb Package Build (amd64, Ubuntu)
        uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0

      - uses: actions/upload-artifact@v1
        with:
          name: artifact-deb
          path: target/x86_64-unknown-linux-musl/debian/*

